<?php
/**
 * @file
 *
 * Install Tasks.
 */

/**
 * {@inheritdoc}
 */
function stanford_person_install() {
  // Disable the core taxonomy_term view if it is enabled.
  $core_taxonomy_view = \Drupal::configFactory()->get('views.view.taxonomy_term');
  if ($core_taxonomy_view->get('status') == TRUE) {
    $editable = \Drupal::configFactory()->getEditable('views.view.taxonomy_term');
    $editable->set('status', FALSE);
    $editable->save();
  }
}
