<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\views\ViewExecutable;
use Drupal\node\NodeInterface;

/**
 * Implements hook_views_pre_render().
 */
function stanford_person_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'stanford_person')) {
    $view->element['#attached']['library'][] = 'stanford_person/views';
  }
}

/**
 * Implements hook_preprocess_node().
 */
function stanford_person_page_attachments(array &$attachments) {
  // Get the node from the route.
  $node = \Drupal::routeMatch()->getParameter('node');

  // Not a node.. Then just continue.
  if (!$node instanceof NodeInterface) {
    return;
  }

  // Check for our type and add library if a match.
  if ($node->getType() == "stanford_person") {
    $attachments['#attached']['library'][] = 'stanford_person/node';
  }
}
