<?php

/**
 * @file
 * Contains stanford_person_importer.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\config_pages\ConfigPagesInterface;

/**
 * Implements hook_help().
 */
function stanford_person_importer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the stanford_person_importer module.
    case 'help.page.stanford_person_importer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration support for importing of profile information from stanford.edu.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Migration callback to just get the current timestamp.
 *
 * We use this function in migration callback processes because using `time` as
 * the callback produces messages about "function accepts 0 arguments, 1
 * argument passed". So we just have our own callback that takes the argument
 * from the migration process and does nothing with it.
 *
 * @param mixed $arg
 *   Passed parameter from migration plugin `callback`.
 *
 * @return int
 *   Current timestamp.
 *
 * @see \Drupal\migrate\Plugin\migrate\process\Callback::transform()
 */
function _stanford_profile_person_get_time($arg = NULL) {
  return time();
}

/**
 * Implements hook_form_alter().
 */
function stanford_person_importer_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  //  dpm($form_id);
  //  dpm($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_person_importer_form_config_pages_stanford_person_importer_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  //$form['su_person_cap_password']['widget'][]
}

/**
 * Implements hook_field_widget_form_alter().
 */
function stanford_person_importer_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  if ($context['items']->getFieldDefinition()
      ->getName() == 'su_person_cap_password') {
    $element['#element_validate'][] = [
      'Drupal\stanford_person_importer\Cap',
      'validateCredentials',
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function stanford_person_importer_config_pages_presave(ConfigPagesInterface $entity) {
  if ($entity->bundle() == 'stanford_person_importer') {
    $terms = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->getQuery()
      ->condition('vid', 'cap_org_codes')
      ->execute();
    if (empty($terms)) {
      \Drupal::service('stanford_person_importer.cap')
        ->setClientId($entity->get('su_person_cap_username')->getString())
        ->setClientSecret($entity->get('su_person_cap_password')->getString())
        ->updateOrganizations();
    }
    Cache::invalidateTags(['migration_plugins']);
  }
}
